# Generated by Django 4.2.6 on 2023-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
