# Generated by Django 4.2.6 on 2023-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_curso_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="contenido",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido del Curso"
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="metodologia",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("presencial", "Presencial"),
                    ("semipresencial", "Semipresencial"),
                ],
                default="online",
                max_length=15,
                verbose_name="Metodología del Curso",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="objetivos",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objetivos del Curso"
            ),
        ),
    ]
