# Generated by Django 4.2.6 on 2023-11-16 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_estudiante_inscripcion_curso_inscripciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="curso",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learning.instructor",
            ),
        ),
    ]
