# Generated by Django 4.2.6 on 2023-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_curso_is_deleted_alter_curso_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatar"),
        ),
    ]
